import { SECTIONS } from './engine/sections';

export function generateGuideHtml(
  familyName: string,
  summaries: Record<string, string>,
): string {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const sectionBlocks = SECTIONS.map(sec => {
    const summary = summaries[sec.id];
    if (!summary) return '';

    // Build linkage sentence from adjacent section context
    const linkages: Record<string, string> = {
      responsibilities: 'Building on the family goals above, here is what the au pair\'s day-to-day work looks like.',
      housemate_expectations: 'Beyond the children\'s routines, here is what daily life in the home looks like for the au pair.',
      household_info: 'Knowing how the home works is an important part of settling in. Here are the practical details.',
      screen_time_media: 'Screen time is one of the areas where the family\'s expectations matter most. Here is what they ask.',
      discipline_philosophy: 'Consistent with the family\'s overall approach, here is how they handle behaviour and discipline.',
    };

    const linkage = linkages[sec.id] ? `<p class="linkage">${linkages[sec.id]}</p>` : '';

    return `
  <section>
    <h2><span class="icon">${sec.icon}</span> ${sec.title}</h2>
    ${linkage}
    <div class="summary-block"><p>${summary.replace(/\n/g, '<br/>')}</p></div>
  </section>`;
  }).filter(Boolean).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Household Guide — ${familyName}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', -apple-system, sans-serif; background: #f8fafc; color: #1a2744; line-height: 1.6; -webkit-font-smoothing: antialiased; }
    .hero { background: linear-gradient(135deg, #1a2744 0%, #1e3a5f 100%); color: #fff; padding: 56px 32px 48px; text-align: center; }
    .hero-logo { font-size: 13px; font-weight: 600; letter-spacing: 3px; text-transform: uppercase; color: #14b8a6; margin-bottom: 20px; }
    .hero h1 { font-size: 40px; font-weight: 800; letter-spacing: -1.5px; line-height: 1.1; }
    .hero .sub { color: #94a3b8; margin-top: 10px; font-size: 16px; }
    .hero .date { color: #475569; margin-top: 20px; font-size: 13px; }
    .container { max-width: 760px; margin: 0 auto; padding: 48px 24px 80px; }
    section { margin-bottom: 56px; }
    h2 { font-size: 20px; font-weight: 700; color: #1a2744; display: flex; align-items: center; gap: 10px; padding-bottom: 12px; border-bottom: 2px solid #14b8a6; margin-bottom: 20px; }
    h2 .icon { font-size: 22px; }
    .linkage { font-size: 14px; color: #64748b; font-style: italic; margin-bottom: 16px; padding-left: 14px; border-left: 3px solid #99f6e4; }
    .summary-block { background: #fff; border-radius: 14px; padding: 22px 26px; border: 1px solid #e2e8f0; font-size: 15px; line-height: 1.85; color: #334155; }
    footer { text-align: center; padding: 32px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 13px; margin-top: 32px; }
    footer strong { color: #14b8a6; }
    .note { font-size: 11px; color: #cbd5e1; margin-top: 6px; display: block; }
    @media print { body { background: white; } .hero { -webkit-print-color-adjust: exact; print-color-adjust: exact; } section { break-inside: avoid; } }
  </style>
</head>
<body>
<div class="hero">
  <div class="hero-logo">Pair</div>
  <h1>${familyName}</h1>
  <p class="sub">Household Guide for our Au Pair</p>
  <p class="date">Generated ${generatedDate}</p>
</div>
<div class="container">
${sectionBlocks}
</div>
<footer>
  Generated by <strong>Pair</strong> · The au pair relationship platform
  <span class="note">This is a living document — ask your family if anything is unclear.</span>
</footer>
</body>
</html>`;
}
