import type { Question, Section } from '@pair/types';

export const disciplinePhilosophyQuestions: Question[] = [
  {
    id: 'discipline_overall_philosophy',
    sectionId: 'discipline_philosophy',
    text: 'How would you describe your overall approach to discipline?',
    subtext: 'This will be shared with your au pair and used as a foundation for performance reviews.',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Our discipline philosophy',
    feedsIntoModules: ['performance_review'],
    placeholder: 'e.g. We believe in natural consequences and active dialogue over punishment. We give advance notice before transitions. When things go wrong, we prioritise connection before correction...',
  },
  {
    id: 'discipline_style',
    sectionId: 'discipline_philosophy',
    text: 'Which approach best describes your household\'s discipline style?',
    answerType: 'multi_choice',
    required: true,
    documentLabel: 'Discipline style',
    feedsIntoModules: ['performance_review'],
    options: [
      { value: 'natural_consequences', label: 'Natural consequences', description: 'Let children experience the consequences of their choices.' },
      { value: 'positive_reinforcement', label: 'Positive reinforcement first', description: 'Reward and praise good behaviour rather than focusing on the bad.' },
      { value: 'time_out', label: 'Time-out or quiet time', description: 'A designated space or time to calm down and reflect.' },
      { value: 'logical_consequences', label: 'Logical consequences', description: 'Consequences that are directly related to the misbehaviour.' },
      { value: 'choice_giving', label: 'Choice-giving', description: 'Offering controlled choices to give the child agency within boundaries.' },
      { value: 'emotion_coaching', label: 'Emotion coaching', description: 'Naming feelings, validating, then problem-solving together.' },
      { value: 'privilege_removal', label: 'Privilege removal', description: 'Losing access to something earned (screen time, a toy) as a consequence.' },
    ],
  },
  {
    id: 'prior_notice_approach',
    sectionId: 'discipline_philosophy',
    text: 'Do you use advance warnings before transitions or consequences?',
    subtext: 'E.g. "5-minute warnings" before screen time ends, or "one more chance" before a consequence.',
    answerType: 'boolean',
    required: true,
    documentLabel: 'Advance warnings',
  },
  {
    id: 'prior_notice_notes',
    sectionId: 'discipline_philosophy',
    text: 'How do you use advance warnings?',
    answerType: 'free_text',
    required: false,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'prior_notice_approach', operator: 'eq', value: true }],
    },
    documentLabel: 'Advance warning approach',
    placeholder: 'e.g. We always give a 5-minute warning before screen time ends. For transitions (leaving the playground, ending playdates), we give 2 warnings — 10 minutes and 5 minutes...',
  },
  {
    id: 'timeout_approach',
    sectionId: 'discipline_philosophy',
    text: 'Do you use time-out or a cool-down space?',
    answerType: 'boolean',
    required: true,
    documentLabel: 'Time-out / cool-down',
  },
  {
    id: 'timeout_notes',
    sectionId: 'discipline_philosophy',
    text: 'Describe how time-out or cool-down works in your household.',
    answerType: 'free_text',
    required: false,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'timeout_approach', operator: 'eq', value: true }],
    },
    documentLabel: 'Time-out / cool-down approach',
    placeholder: 'e.g. "Thinking spot" is the small chair in the hallway. 1 minute per year of age. After, we come together and talk about what happened — no lingering on it...',
  },
  {
    id: 'positive_reinforcement_approach',
    sectionId: 'discipline_philosophy',
    text: 'How do you handle positive reinforcement and reward?',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Positive reinforcement',
    feedsIntoModules: ['performance_review'],
    placeholder: 'e.g. We use a sticker chart for Emma — 10 stickers earns a small treat she picks. For Lucas, verbal praise is enough. We avoid food as reward...',
  },
  {
    id: 'hard_rules',
    sectionId: 'discipline_philosophy',
    text: 'What are the absolute hard rules in your household?',
    subtext: 'Non-negotiable rules where there is no flexibility. The au pair should understand these clearly.',
    answerType: 'multi_text',
    required: true,
    documentLabel: 'Hard rules',
    feedsIntoModules: ['performance_review'],
    placeholder: 'Add a rule...',
  },
  {
    id: 'physical_discipline_stance',
    sectionId: 'discipline_philosophy',
    text: 'What is your stance on physical discipline (smacking, physical restraint)?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Physical discipline',
    options: [
      { value: 'absolutely_not', label: 'Absolutely not — under any circumstances' },
      { value: 'not_by_au_pair', label: 'Not by the au pair — family handles these situations' },
      { value: 'discuss', label: 'I\'d like to discuss this' },
    ],
  },
  {
    id: 'what_not_to_do',
    sectionId: 'discipline_philosophy',
    text: 'Are there specific discipline approaches you would not want the au pair to use?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'What not to do',
    feedsIntoModules: ['performance_review'],
    placeholder: 'e.g. Please never threaten consequences we haven\'t agreed on. Don\'t use food as a reward or punishment. Don\'t shame or compare siblings...',
  },
  {
    id: 'escalation_protocol',
    sectionId: 'discipline_philosophy',
    text: 'If a situation escalates beyond what the au pair can manage, what should they do?',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Escalation — what to do',
    placeholder: 'e.g. First, ensure everyone is physically safe. Then text one of us — we\'ll always respond quickly. Don\'t escalate a power struggle alone. You can always say "I need to talk to mum/dad about this first"...',
  },
  {
    id: 'discipline_debrief',
    sectionId: 'discipline_philosophy',
    text: 'How would you like the au pair to communicate discipline incidents to you?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Discipline communication',
    options: [
      { value: 'realtime', label: 'Text immediately for anything significant' },
      { value: 'end_of_day', label: 'End-of-day verbal update' },
      { value: 'app_log', label: 'Log in the app — we\'ll review' },
      { value: 'only_if_major', label: 'Only if something major — trust your judgement' },
    ],
    feedsIntoModules: ['performance_review'],
  },

  // ── Per-child: special needs ───────────────────────────────────────────────
  {
    id: 'child_special_needs_discipline',
    sectionId: 'discipline_philosophy',
    text: 'How does {childName}\'s additional needs affect discipline and behaviour management?',
    subtext: 'Include any specific strategies, triggers to avoid, or how the general approach should be adapted.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.special_needs', operator: 'eq', value: true }],
    },
    documentLabel: 'Discipline approach for additional needs',
    feedsIntoModules: ['performance_review', 'handover'],
    placeholder: 'e.g. For Lucas\'s ADHD, transitions are the hardest moments. 10-minute warning is essential. Don\'t raise your voice — it escalates. Walk away and re-approach calmly. Never take away his fidget tools...',
  },
  {
    id: 'child_therapist_coordination',
    sectionId: 'discipline_philosophy',
    text: 'Does {childName} work with a therapist, counsellor, or specialist we should inform the au pair about?',
    answerType: 'boolean',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.special_needs', operator: 'eq', value: true }],
    },
    documentLabel: 'Specialist coordination',
  },
  {
    id: 'child_therapist_notes',
    sectionId: 'discipline_philosophy',
    text: 'Any relevant details about {childName}\'s specialist or therapy schedule the au pair should know?',
    answerType: 'free_text',
    required: false,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [
        { sourceQuestionId: '_repeat_context.special_needs', operator: 'eq', value: true },
        { sourceQuestionId: 'child_therapist_coordination', operator: 'eq', value: true },
      ],
    },
    documentLabel: 'Specialist notes',
    feedsIntoModules: ['scheduling', 'handover'],
    placeholder: 'e.g. Lucas sees Dr. Chen for OT every Tuesday at 4pm. Au pair drives him. Sensory activities after OT help regulate — swing time or clay...',
  },

  // ── Closing ─────────────────────────────────────────────────────────────────
  {
    id: 'discipline_anything_else',
    sectionId: 'discipline_philosophy',
    text: 'Is there anything else about your household\'s approach to children\'s behaviour that the au pair should understand?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Discipline — anything else',
    placeholder: 'e.g. We believe strongly in not discussing consequences in the heat of the moment. If you\'re unsure, buy time — "let me think about that" — and talk to us...',
  },
];

export const disciplinePhilosophySection: Section = {
  id: 'discipline_philosophy',
  title: 'Discipline Philosophy',
  description: 'Document your approach to children\'s behaviour — this feeds directly into performance reviews and ensures the au pair and family are fully aligned.',
  icon: '💬',
  estimatedMinutes: 12,
  questions: disciplinePhilosophyQuestions,
};
