import type { Question, Section } from '@pair/types';

export const familyGoalsQuestions: Question[] = [
  {
    id: 'family_name',
    sectionId: 'family_goals',
    text: 'What is your family name? (e.g. "The Johnson Family")',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Family name',
    placeholder: 'e.g. The Johnson Family',
  },
  {
    id: 'family_intro',
    sectionId: 'family_goals',
    text: 'Write a short introduction to your family — who you are, where you live, and what makes your home special.',
    subtext: 'This will appear at the top of your household guide. Write as if introducing yourselves to your incoming au pair.',
    answerType: 'free_text',
    required: true,
    documentLabel: 'About our family',
    placeholder: 'e.g. We\'re a family of four in Brookline, MA. We love hiking, cooking together, and our slightly chaotic weekend mornings...',
  },
  {
    id: 'primary_language',
    sectionId: 'family_goals',
    text: 'What language does your family primarily speak at home?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Primary language',
    options: [
      { value: 'english', label: 'English' },
      { value: 'spanish', label: 'Spanish' },
      { value: 'french', label: 'French' },
      { value: 'mandarin', label: 'Mandarin' },
      { value: 'other', label: 'Other' },
    ],
    feedsIntoModules: ['scheduling'],
  },
  {
    id: 'additional_languages',
    sectionId: 'family_goals',
    text: 'Are there any other languages spoken regularly in your home?',
    answerType: 'multi_choice',
    required: false,
    documentLabel: 'Additional languages',
    options: [
      { value: 'english', label: 'English' },
      { value: 'spanish', label: 'Spanish' },
      { value: 'french', label: 'French' },
      { value: 'mandarin', label: 'Mandarin' },
      { value: 'arabic', label: 'Arabic' },
      { value: 'portuguese', label: 'Portuguese' },
      { value: 'german', label: 'German' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'childcare_style',
    sectionId: 'family_goals',
    text: 'How would you describe your approach to childcare?',
    subtext: 'Choose the description that feels most like your household.',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Childcare style',
    options: [
      { value: 'child_led', label: 'Child-led', description: 'We follow the children\'s cues and let them guide their own play and learning.' },
      { value: 'structured', label: 'Structured', description: 'We rely on consistent routines, schedules, and clear expectations.' },
      { value: 'balanced', label: 'Balanced', description: 'A mix — structured for sleep and meals, flexible for play and activities.' },
      { value: 'educational', label: 'Educationally focused', description: 'We prioritise learning opportunities, enrichment, and skill development.' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'household_style',
    sectionId: 'family_goals',
    text: 'How would you describe the overall feel of your household?',
    answerType: 'scale',
    required: true,
    scaleConfig: { min: 1, max: 5, minLabel: 'Very relaxed — go with the flow', maxLabel: 'Very structured — clear rules and expectations' },
    documentLabel: 'Household style',
    feedsIntoModules: ['performance_review'],
    tags: ['household_style_scale'],
  },
  {
    id: 'cultural_exchange_emphasis',
    sectionId: 'family_goals',
    text: 'How important is cultural exchange to your family?',
    answerType: 'scale',
    required: true,
    scaleConfig: { min: 1, max: 5, minLabel: 'Not a priority — primarily practical childcare', maxLabel: 'Central to why we host — a genuine two-way exchange' },
    documentLabel: 'Cultural exchange emphasis',
    tags: ['cultural_emphasis_scale'],
  },
  {
    id: 'cultural_exchange_goals',
    sectionId: 'family_goals',
    text: 'What do you hope your children will gain from having an au pair from another culture?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Cultural exchange goals',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'cultural_exchange_emphasis', operator: 'gte', value: 3 }],
    },
    placeholder: 'e.g. Exposure to another language, broader worldview, learning that families live differently around the world...',
  },
  {
    id: 'au_pair_cultural_participation',
    sectionId: 'family_goals',
    text: 'To what extent do you want the au pair to participate in family life beyond working hours?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Au pair participation in family life',
    options: [
      { value: 'full_member', label: 'Full family member', description: 'Invited to meals, outings, and family events as part of the family.' },
      { value: 'welcome_but_own_space', label: 'Welcome but independent', description: 'Invited when it makes sense; otherwise has full independence.' },
      { value: 'professional', label: 'More professional arrangement', description: 'Clear separation between working and personal time on both sides.' },
    ],
  },
  {
    id: 'communication_style',
    sectionId: 'family_goals',
    text: 'What is your preferred communication style with the au pair?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Communication preference',
    options: [
      { value: 'direct', label: 'Direct and in the moment', description: 'We prefer to address things immediately and directly, face to face.' },
      { value: 'collaborative', label: 'Collaborative check-ins', description: 'Regular scheduled conversations to discuss anything that\'s come up.' },
      { value: 'written_first', label: 'Written first', description: 'We prefer to capture things in writing (app, text) and then discuss.' },
    ],
    feedsIntoModules: ['performance_review'],
    tags: ['communication_style'],
  },
  {
    id: 'check_in_frequency',
    sectionId: 'family_goals',
    text: 'How often would you like formal check-ins with your au pair?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Check-in frequency',
    options: [
      { value: 'weekly', label: 'Weekly', description: 'A short weekly sit-down — good for the first few months especially.' },
      { value: 'biweekly', label: 'Every two weeks', description: 'Regular but not too frequent.' },
      { value: 'monthly', label: 'Monthly', description: 'Monthly structured conversation.' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'top_priorities',
    sectionId: 'family_goals',
    text: 'What are your top three priorities for this au pair year?',
    subtext: 'These will be shared with your au pair and used as the foundation for performance reviews.',
    answerType: 'multi_choice',
    required: true,
    documentLabel: 'Family priorities for this year',
    options: [
      { value: 'safe_reliable_care', label: 'Safe, reliable childcare' },
      { value: 'school_support', label: 'School support and homework help' },
      { value: 'language_development', label: 'Language development in children' },
      { value: 'cultural_exchange', label: 'Genuine cultural exchange' },
      { value: 'household_partnership', label: 'Household partnership' },
      { value: 'flexibility', label: 'Scheduling flexibility' },
      { value: 'social_development', label: 'Social and emotional development for children' },
      { value: 'activities', label: 'Enrichment activities and outdoor time' },
    ],
    feedsIntoModules: ['performance_review'],
  },
];

export const familyGoalsSection: Section = {
  id: 'family_goals',
  title: 'Family Goals',
  description: 'Tell us about your family and what you\'re hoping to achieve this year. This becomes the opening of your household guide.',
  icon: '🏡',
  estimatedMinutes: 10,
  questions: familyGoalsQuestions,
};
