import type { Question, Section } from '@pair/types';

export const housemateExpectationsQuestions: Question[] = [
  {
    id: 'meals_policy',
    sectionId: 'housemate_expectations',
    text: 'What is your policy on meals for the au pair?',
    subtext: 'This is one of the most common sources of uncertainty. Be specific.',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Meals policy',
    options: [
      { value: 'full_family_meals', label: 'All meals provided', description: 'The au pair eats all meals with or alongside the family. Groceries are fully provided.' },
      { value: 'family_groceries', label: 'Family groceries shared', description: 'The au pair may use family groceries freely and is welcome at family meals.' },
      { value: 'designated_food', label: 'Designated au pair food', description: 'We buy specific food for the au pair. Family food is separate.' },
      { value: 'stipend_covers', label: 'Own food from stipend', description: 'The au pair is responsible for their own food. Stipend accounts for this.' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'meals_nuance',
    sectionId: 'housemate_expectations',
    text: 'Any nuance to your meals arrangement worth explaining?',
    subtext: 'E.g. welcome at family dinners but mornings are independent, specific items that are off-limits, guest policy at meals.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Meals — additional notes',
    placeholder: 'e.g. Always welcome at family dinner. Morning breakfast is independent. Please don\'t use the cold brew concentrate — that\'s for the parents.',
  },
  {
    id: 'kitchen_cleanup',
    sectionId: 'housemate_expectations',
    text: 'What are your kitchen clean-up expectations?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Kitchen clean-up',
    options: [
      { value: 'clean_as_you_go', label: 'Clean as you go', description: 'Wash up immediately after use — don\'t leave dishes in the sink.' },
      { value: 'same_day', label: 'Same day', description: 'Clean up by end of the day.' },
      { value: 'dishwasher_ok', label: 'Dishwasher is fine', description: 'Rinse and load the dishwasher. Run it when full.' },
      { value: 'flexible', label: 'Flexible', description: 'No specific rule — use common sense and keep things tidy.' },
    ],
  },
  {
    id: 'kitchen_cleanup_notes',
    sectionId: 'housemate_expectations',
    text: 'Any specific kitchen rules to mention?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Kitchen notes',
    placeholder: 'e.g. Always wipe the stovetop after cooking. Don\'t leave food in the sink trap. The dishwasher runs on eco mode — takes 2 hours, don\'t interrupt it...',
  },
  {
    id: 'room_standards',
    sectionId: 'housemate_expectations',
    text: 'What are your expectations for the au pair\'s room and bathroom?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Room and bathroom standards',
    options: [
      { value: 'private_space', label: 'Fully private — no entry without notice', description: 'The au pair\'s space is their own. We knock and ask before entering.' },
      { value: 'tidy_common', label: 'Private room, shared bathroom must be tidy', description: 'Room is private; shared bathroom areas must be kept clear after use.' },
      { value: 'weekly_check', label: 'Weekly tidy expected for shared areas', description: 'Common bathroom areas should be cleaned weekly. Room is private.' },
    ],
  },
  {
    id: 'room_standards_notes',
    sectionId: 'housemate_expectations',
    text: 'Any specific notes on the au pair\'s room or bathroom?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Room notes',
    placeholder: 'e.g. Please keep the shared bathroom counter clear after use. Bathroom towels are changed weekly. Please don\'t bring food into your room...',
  },
  {
    id: 'common_areas',
    sectionId: 'housemate_expectations',
    text: 'What are your expectations for common areas (living room, kitchen, garden)?',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Common area expectations',
    placeholder: 'e.g. Living room is shared — feel free to use it when the family is not home. Please tidy before bed. The garden is fully available. No shoes inside the house...',
  },
  {
    id: 'personal_curfew',
    sectionId: 'housemate_expectations',
    text: 'Do you have a curfew for the au pair on working days?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Weekday curfew',
    options: [
      { value: 'no_curfew', label: 'No curfew', description: 'No specific time requirement, as long as work isn\'t affected.' },
      { value: 'midnight', label: 'Midnight', description: 'Home by midnight on work nights.' },
      { value: 'eleven_pm', label: '11pm', description: 'Home by 11pm on work nights.' },
      { value: 'ten_pm', label: '10pm', description: 'Home by 10pm on work nights.' },
      { value: 'other', label: 'Other — I\'ll describe it', description: 'A nuanced policy I\'ll explain below.' },
    ],
  },
  {
    id: 'curfew_notes',
    sectionId: 'housemate_expectations',
    text: 'Describe your curfew policy.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Curfew notes',
    showIf: {
      logic: 'OR',
      conditions: [
        { sourceQuestionId: 'personal_curfew', operator: 'eq', value: 'other' },
        { sourceQuestionId: 'personal_curfew', operator: 'neq', value: 'no_curfew' },
      ],
    },
    placeholder: 'e.g. No formal curfew but please be home by midnight if you work the next morning. Let us know if you\'ll be very late so we\'re not worried...',
  },
  {
    id: 'weekend_curfew',
    sectionId: 'housemate_expectations',
    text: 'Do you have a curfew on weekend nights (when not working the next morning)?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Weekend curfew',
    options: [
      { value: 'no_curfew', label: 'No curfew on weekends' },
      { value: 'same_as_weekday', label: 'Same as weekdays' },
      { value: 'later', label: 'Later — I\'ll describe' },
    ],
  },
  {
    id: 'visitor_policy',
    sectionId: 'housemate_expectations',
    text: 'What is your policy on visitors to the home?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Visitor policy',
    options: [
      { value: 'open', label: 'Open — guests welcome anytime with notice', description: 'Friends are welcome. Let us know in advance so we\'re not surprised.' },
      { value: 'limited_times', label: 'Guests welcome during certain hours', description: 'Daytime and early evening guests are fine. Late-night visitors require discussion.' },
      { value: 'discuss_first', label: 'Please discuss first', description: 'Any guests coming to the house should be discussed with us first.' },
      { value: 'no_visitors', label: 'No regular visitors', description: 'We prefer the home to be a private family space.' },
    ],
  },
  {
    id: 'visitor_notes',
    sectionId: 'housemate_expectations',
    text: 'Any additional notes on the visitor policy?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Visitor notes',
    placeholder: 'e.g. Friends are welcome for dinner or a quiet evening. Please let us know the same day. Children\'s friends during working hours need to be agreed in advance...',
  },
  {
    id: 'overnight_guests',
    sectionId: 'housemate_expectations',
    text: 'What is your policy on overnight guests in the au pair\'s room?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Overnight guest policy',
    options: [
      { value: 'allowed_with_notice', label: 'Allowed with advance notice', description: 'Occasional overnight guests are fine — let us know beforehand.' },
      { value: 'limited', label: 'Limited — occasional only', description: 'Occasional overnight guests, by agreement. Not regularly.' },
      { value: 'not_allowed', label: 'Not allowed', description: 'Overnight guests in the au pair\'s room are not permitted.' },
    ],
  },
  {
    id: 'noise_quiet_hours',
    sectionId: 'housemate_expectations',
    text: 'Do you have quiet hours in the house?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Quiet hours',
    placeholder: 'e.g. After 9:30pm on weeknights when children are asleep. Loud music or TV in common areas should be kept low. Your room is your own.',
  },
  {
    id: 'smoking_policy',
    sectionId: 'housemate_expectations',
    text: 'What is your smoking policy?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Smoking policy',
    options: [
      { value: 'no_smoking', label: 'No smoking — on or off the property' },
      { value: 'outside_only', label: 'Outside only — not near the children' },
      { value: 'not_a_concern', label: 'No specific restriction' },
    ],
  },
  {
    id: 'personal_space_philosophy',
    sectionId: 'housemate_expectations',
    text: 'Is there anything else about living in your home that an au pair should know?',
    subtext: 'E.g. family routines, privacy norms, how you handle quiet time, anything that would help someone settle in.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Living in our home — other notes',
    placeholder: 'e.g. We\'re morning people — the house is usually quiet by 9pm. Feel free to use the backyard any time. We value privacy but love a good Friday dinner together...',
  },
];

export const housemateExpectationsSection: Section = {
  id: 'housemate_expectations',
  title: 'Housemate Expectations',
  description: 'Define what living in your home looks like — meals, common areas, curfew, and visitor policy.',
  icon: '🤝',
  estimatedMinutes: 12,
  questions: housemateExpectationsQuestions,
};
