import type { Question, Section } from '@pair/types';

export const householdInfoQuestions: Question[] = [
  {
    id: 'wifi_name',
    sectionId: 'household_info',
    text: 'What is the WiFi network name (SSID)?',
    answerType: 'free_text',
    required: true,
    documentLabel: 'WiFi name',
    placeholder: 'e.g. JohnsonFamily5G',
  },
  {
    id: 'wifi_password',
    sectionId: 'household_info',
    text: 'What is the WiFi password?',
    answerType: 'free_text',
    required: true,
    documentLabel: 'WiFi password',
    placeholder: 'e.g. SunshineHill2024!',
  },
  {
    id: 'appliances_overview',
    sectionId: 'household_info',
    text: 'Which appliances does the au pair need to know how to use?',
    subtext: 'Select all that apply. We\'ll ask for brief instructions for each.',
    answerType: 'multi_choice',
    required: true,
    documentLabel: 'Appliances',
    options: [
      { value: 'washing_machine', label: 'Washing machine' },
      { value: 'dryer', label: 'Tumble dryer' },
      { value: 'dishwasher', label: 'Dishwasher' },
      { value: 'oven', label: 'Oven / range' },
      { value: 'microwave', label: 'Microwave' },
      { value: 'coffee_machine', label: 'Coffee machine' },
      { value: 'robot_vacuum', label: 'Robot vacuum' },
      { value: 'car_seat', label: 'Car seat installation' },
      { value: 'alarm_system', label: 'Alarm / security system' },
      { value: 'smart_home', label: 'Smart home system (lights, locks, etc.)' },
    ],
  },
  {
    id: 'washing_machine_instructions',
    sectionId: 'household_info',
    text: 'Washing machine instructions.',
    subtext: 'Which programme to use, what setting for delicates, any quirks.',
    answerType: 'free_text',
    required: true,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'appliances_overview', operator: 'includes', value: 'washing_machine' }],
    },
    documentLabel: 'Washing machine',
    placeholder: 'e.g. Use "Cotton 40°" for most loads. Delicates on "Gentle 30°". Don\'t overfill — max 3/4 full. Detergent goes in the left drawer...',
  },
  {
    id: 'dryer_instructions',
    sectionId: 'household_info',
    text: 'Dryer instructions.',
    subtext: 'Settings, what not to tumble dry, filter cleaning.',
    answerType: 'free_text',
    required: true,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'appliances_overview', operator: 'includes', value: 'dryer' }],
    },
    documentLabel: 'Dryer',
    placeholder: 'e.g. Medium heat for most items. Hang dry school uniforms and anything with "do not tumble dry" on the label. Clean the lint filter after every load...',
  },
  {
    id: 'dishwasher_instructions',
    sectionId: 'household_info',
    text: 'Dishwasher instructions.',
    answerType: 'free_text',
    required: true,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'appliances_overview', operator: 'includes', value: 'dishwasher' }],
    },
    documentLabel: 'Dishwasher',
    placeholder: 'e.g. Rinse off food before loading. Don\'t put wooden items, good knives, or cast iron inside. Dishwasher tablets are under the sink. Run on "Eco" when full...',
  },
  {
    id: 'oven_instructions',
    sectionId: 'household_info',
    text: 'Oven / range instructions.',
    answerType: 'free_text',
    required: false,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'appliances_overview', operator: 'includes', value: 'oven' }],
    },
    documentLabel: 'Oven / range',
    placeholder: 'e.g. Gas hob — turn dials fully counterclockwise to light. Oven: always preheat 10 minutes. Self-cleans if left on 450°F for 1 hour (do this monthly)...',
  },
  {
    id: 'alarm_system_instructions',
    sectionId: 'household_info',
    text: 'Alarm / security system instructions.',
    subtext: 'Include the code, how to arm/disarm, and what to do if it goes off accidentally.',
    answerType: 'free_text',
    required: true,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'appliances_overview', operator: 'includes', value: 'alarm_system' }],
    },
    documentLabel: 'Security system',
    placeholder: 'e.g. Code is 4219. Arm when leaving: press "Away". Disarm on entry: 30 seconds before alarm sounds. If it trips accidentally, call [Company] at 800-xxx-xxxx and quote account #...',
  },
  {
    id: 'car_seat_instructions',
    sectionId: 'household_info',
    text: 'Car seat installation notes.',
    subtext: 'Include which seat is for which child, how to install if removed, and any quirks.',
    answerType: 'free_text',
    required: false,
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'appliances_overview', operator: 'includes', value: 'car_seat' }],
    },
    documentLabel: 'Car seat',
    placeholder: 'e.g. Emma\'s seat is the grey Graco in the middle. Lucas uses the booster on the right. If removed, there\'s a card in the seat manual in the glove box with installation steps...',
  },
  {
    id: 'other_appliance_notes',
    sectionId: 'household_info',
    text: 'Any other appliances or household systems worth explaining?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Other appliance notes',
    placeholder: 'e.g. The Nest thermostat: tap the ring to wake it. Set to 68°F when home, 65°F at night. Don\'t override the schedule — talk to us first...',
  },
  {
    id: 'hvac_instructions',
    sectionId: 'household_info',
    text: 'Heating and cooling instructions.',
    subtext: 'How to adjust the temperature, any seasonal guidance, what not to do.',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Heating & cooling',
    placeholder: 'e.g. Thermostat is in the hallway. Set to 68°F in winter, 72°F in summer. Don\'t open windows when AC is running. In summer, close blinds in the front rooms by 10am...',
  },
  {
    id: 'emergency_contacts',
    sectionId: 'household_info',
    text: 'Emergency contacts.',
    subtext: 'Add the key people the au pair should be able to reach in any situation.',
    answerType: 'structured_list',
    required: true,
    documentLabel: 'Emergency contacts',
    feedsIntoModules: ['scheduling', 'handover'],
  },
  {
    id: 'nearest_hospital',
    sectionId: 'household_info',
    text: 'What is the nearest hospital or urgent care centre?',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Nearest hospital / urgent care',
    placeholder: 'e.g. Mass General Hospital — 55 Fruit St, Boston. 617-726-2000. ER entrance on Blossom St.',
  },
  {
    id: 'doctor_info',
    sectionId: 'household_info',
    text: 'Children\'s doctor details.',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Children\'s doctor',
    placeholder: 'e.g. Dr. Sarah Kim at Boston Children\'s Pediatrics. 617-355-6000. Address: 333 Longwood Ave. Insurance card is in the kitchen junk drawer...',
  },
  {
    id: 'key_addresses',
    sectionId: 'household_info',
    text: 'Any other important addresses (school, sports club, regular pharmacy, etc.)?',
    answerType: 'structured_list',
    required: false,
    documentLabel: 'Key addresses',
  },
  {
    id: 'safety_notes',
    sectionId: 'household_info',
    text: 'Anything specific about the home\'s safety setup the au pair should know?',
    subtext: 'E.g. pool rules, door locks, baby gates, neighbourhood notes.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Safety notes',
    placeholder: 'e.g. Pool gate must be latched at all times when children are outside. Front door deadbolt needs a firm push while turning the key. No children in the garage unsupervised...',
  },
  {
    id: 'house_rules_other',
    sectionId: 'household_info',
    text: 'Is there anything else about the house that would take time to explain in person?',
    subtext: 'Anything a new person would need to figure out the hard way without this guide.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'House — other notes',
    placeholder: 'e.g. The hot water takes 30 seconds to run in the upstairs bathroom. The porch door lock needs to be lifted before turning. The recycling goes out Tuesday nights...',
  },
];

export const householdInfoSection: Section = {
  id: 'household_info',
  title: 'Household Info',
  description: 'Capture the practical details of your home — appliances, systems, contacts — once. Your au pair will always know where to find them.',
  icon: '🏠',
  estimatedMinutes: 15,
  questions: householdInfoQuestions,
};
