import type { Question, Section } from '@pair/types';

export const responsibilitiesQuestions: Question[] = [
  // ── Children setup ──────────────────────────────────────────────────────────
  {
    id: 'children_list',
    sectionId: 'responsibilities',
    text: 'Tell us about your children. Add each child the au pair will care for.',
    subtext: 'We\'ll ask follow-up questions for each child. You can add up to 6 children.',
    answerType: 'structured_list',
    required: true,
    documentLabel: 'Children',
    feedsIntoModules: ['scheduling', 'performance_review', 'summer_planner', 'handover'],
  },

  // ── Per-child: always shown ──────────────────────────────────────────────────
  {
    id: 'child_school_pickup',
    sectionId: 'responsibilities',
    text: 'Does {childName} need to be picked up from school or daycare?',
    answerType: 'boolean',
    required: true,
    repeatFor: 'children_list',
    documentLabel: 'School/daycare pick-up',
    feedsIntoModules: ['scheduling'],
  },
  {
    id: 'child_school_pickup_details',
    sectionId: 'responsibilities',
    text: 'Describe the pick-up routine for {childName}.',
    subtext: 'Include school name, address, pick-up time, any car line instructions, who to check in with, and what to bring.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'child_school_pickup', operator: 'eq', value: true }],
    },
    documentLabel: 'Pick-up instructions',
    feedsIntoModules: ['scheduling'],
    placeholder: 'e.g. Pick up from Lincoln Elementary at 3:15pm. Join the car line on Oak Street. Emma\'s teacher is Ms. Rivera — check in at the classroom door...',
  },

  // ── Per-child: toddler/baby (under 5) ──────────────────────────────────────
  {
    id: 'child_nap_schedule',
    sectionId: 'responsibilities',
    text: 'Describe {childName}\'s nap schedule.',
    subtext: 'Include timing, duration, and any pre-nap routine (e.g. book, white noise, specific stuffed animal).',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.age_months', operator: 'lt', value: 60 }],
    },
    documentLabel: 'Nap schedule',
    feedsIntoModules: ['scheduling', 'summer_planner'],
    placeholder: 'e.g. Nap at 12:30pm for 1.5–2 hours. Darken room, white noise machine on, favourite blanket. No screens before nap.',
  },
  {
    id: 'child_feeding_routine',
    sectionId: 'responsibilities',
    text: 'Describe {childName}\'s feeding routine.',
    subtext: 'For babies: bottle/breastfeeding schedule, amount, preparation. For toddlers: meal times, preferred foods, self-feeding stage.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.age_months', operator: 'lt', value: 36 }],
    },
    documentLabel: 'Feeding routine',
    feedsIntoModules: ['scheduling'],
    placeholder: 'e.g. 7oz formula bottle at 7am, 11am, 3pm, 7pm. Formula is in the pantry cupboard. Always burp after...',
  },
  {
    id: 'child_bedtime_routine',
    sectionId: 'responsibilities',
    text: 'What is {childName}\'s bedtime routine?',
    subtext: 'Step-by-step from wind-down to lights out. The au pair may be handling this solo.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    documentLabel: 'Bedtime routine',
    feedsIntoModules: ['scheduling'],
    placeholder: 'e.g. Bath at 6:45pm. Pyjamas, 2 books of her choosing. Lights out by 7:30pm. Leave door ajar with hall light on. She usually settles within 10 minutes...',
  },
  {
    id: 'child_potty_status',
    sectionId: 'responsibilities',
    text: 'What is {childName}\'s potty training status?',
    answerType: 'single_choice',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.age_months', operator: 'lt', value: 60 }],
    },
    documentLabel: 'Potty / nappy status',
    options: [
      { value: 'nappies', label: 'Still in nappies/diapers' },
      { value: 'training', label: 'Currently training — accidents happen' },
      { value: 'trained_day', label: 'Trained during the day, nappy at night' },
      { value: 'fully_trained', label: 'Fully trained' },
    ],
  },
  {
    id: 'child_potty_notes',
    sectionId: 'responsibilities',
    text: 'Any notes on {childName}\'s potty routine or what to do during accidents?',
    answerType: 'free_text',
    required: false,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'child_potty_status', operator: 'includes', value: ['training', 'trained_day'] }],
    },
    documentLabel: 'Potty notes',
    placeholder: 'e.g. She usually needs to go 20 minutes after meals. Accidents: change immediately, don\'t make a big deal of it. Spare clothes in the bottom drawer...',
  },

  // ── Per-child: school age (5+) ─────────────────────────────────────────────
  {
    id: 'child_homework_support',
    sectionId: 'responsibilities',
    text: 'Does {childName} need homework support from the au pair?',
    answerType: 'boolean',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.age_months', operator: 'gte', value: 60 }],
    },
    documentLabel: 'Homework support',
  },
  {
    id: 'child_homework_details',
    sectionId: 'responsibilities',
    text: 'Describe what homework support looks like for {childName}.',
    subtext: 'How much time typically, which subjects need help, when it should happen, and your expectations for how much help to give.',
    answerType: 'free_text',
    required: false,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'child_homework_support', operator: 'eq', value: true }],
    },
    documentLabel: 'Homework support details',
    placeholder: 'e.g. 30–45 minutes of homework after snack (4pm). Math and reading. Encourage her to try first, then help if stuck. Don\'t just give answers...',
  },
  {
    id: 'child_after_school_routine',
    sectionId: 'responsibilities',
    text: 'What is the after-school routine for {childName}?',
    subtext: 'What happens between pick-up and when the parents return. Include snack, activities, screen time, homework.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.age_months', operator: 'gte', value: 60 }],
    },
    documentLabel: 'After-school routine',
    feedsIntoModules: ['scheduling'],
    placeholder: 'e.g. Arrive home 3:30pm. Snack at the kitchen table. Free play until 4pm. Homework 4–4:45pm. Outside time if weather allows. Screen time 5–5:30pm...',
  },

  // ── Household responsibilities (all households) ───────────────────────────
  {
    id: 'childcare_duties_overview',
    sectionId: 'responsibilities',
    text: 'Which of the following childcare duties are part of the au pair role?',
    subtext: 'Select all that apply. We\'ll ask for more detail on the important ones.',
    answerType: 'multi_choice',
    required: true,
    documentLabel: 'Childcare duties',
    options: [
      { value: 'morning_routine', label: 'Morning routine (wake, dress, breakfast)' },
      { value: 'school_pickup', label: 'School / daycare pick-up' },
      { value: 'after_school', label: 'After-school supervision' },
      { value: 'bedtime', label: 'Bedtime routine' },
      { value: 'activity_transport', label: 'Activity transport (sports, lessons)' },
      { value: 'meal_prep_children', label: 'Meal preparation for children' },
      { value: 'homework_support', label: 'Homework support' },
      { value: 'playdates', label: 'Organising / supervising playdates' },
      { value: 'overnight_care', label: 'Overnight care (parents travelling)' },
    ],
  },
  {
    id: 'children_laundry',
    sectionId: 'responsibilities',
    text: 'Is the au pair responsible for children\'s laundry?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Children\'s laundry',
    options: [
      { value: 'full_responsibility', label: 'Yes — wash, dry, fold and put away' },
      { value: 'wash_only', label: 'Yes — wash and dry; family handles folding' },
      { value: 'not_responsible', label: 'No — family handles laundry' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'laundry_instructions',
    sectionId: 'responsibilities',
    text: 'Describe any important laundry instructions for the children\'s clothes.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Laundry instructions',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'children_laundry', operator: 'neq', value: 'not_responsible' }],
    },
    placeholder: 'e.g. Cold wash for everything. Hang dry the school uniforms — don\'t tumble dry. Fold and put away in the children\'s drawers by Friday...',
  },
  {
    id: 'food_prep_responsibility',
    sectionId: 'responsibilities',
    text: 'What food preparation is the au pair responsible for?',
    answerType: 'multi_choice',
    required: true,
    documentLabel: 'Food preparation responsibilities',
    options: [
      { value: 'children_breakfast', label: 'Children\'s breakfast' },
      { value: 'children_lunch', label: 'Children\'s lunch' },
      { value: 'children_snacks', label: 'Children\'s snacks' },
      { value: 'children_dinner', label: 'Children\'s dinner' },
      { value: 'school_packed_lunch', label: 'Packed school lunch' },
      { value: 'family_dinner', label: 'Family dinner (parents included)' },
      { value: 'none', label: 'None — family handles all food prep' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'food_prep_notes',
    sectionId: 'responsibilities',
    text: 'Any important notes about meal preparation?',
    subtext: 'Dietary restrictions, allergies, preferred snacks, cooking style expectations.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Meal prep notes',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'food_prep_responsibility', operator: 'excludes', value: 'none' }],
    },
    placeholder: 'e.g. Emma is gluten-free. Lucas has a nut allergy — nothing with nuts. Simple, wholesome meals. A weekly meal plan is in the kitchen...',
  },
  {
    id: 'seasonal_tasks',
    sectionId: 'responsibilities',
    text: 'Are there any seasonal or one-off household tasks you\'d like help with?',
    answerType: 'multi_choice',
    required: false,
    documentLabel: 'Seasonal and additional tasks',
    options: [
      { value: 'summer_garden', label: 'Summer: garden watering / outdoor tidying' },
      { value: 'back_to_school', label: 'Back-to-school: labelling, supply shopping' },
      { value: 'holiday_prep', label: 'Holiday: decorating, gift wrapping' },
      { value: 'spring_clean', label: 'Spring: wardrobe sort, toy declutter' },
      { value: 'grocery_run', label: 'Grocery runs (with or without children)' },
      { value: 'other', label: 'Other (describe below)' },
    ],
  },
  {
    id: 'seasonal_tasks_other',
    sectionId: 'responsibilities',
    text: 'Describe any other seasonal or additional tasks.',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Other tasks',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'seasonal_tasks', operator: 'includes', value: 'other' }],
    },
  },
  {
    id: 'has_car_access',
    sectionId: 'responsibilities',
    text: 'Will the au pair have access to a family car?',
    answerType: 'boolean',
    required: true,
    documentLabel: 'Car access',
    tags: ['has_car'],
    feedsIntoModules: ['scheduling'],
  },
  {
    id: 'car_driving_expectations',
    sectionId: 'responsibilities',
    text: 'What will the au pair drive the children to?',
    answerType: 'multi_choice',
    required: false,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: 'has_car_access', operator: 'eq', value: true }],
    },
    documentLabel: 'Driving responsibilities',
    options: [
      { value: 'school_pickup', label: 'School / daycare pick-up' },
      { value: 'activities', label: 'Extracurricular activities' },
      { value: 'playdates', label: 'Playdates' },
      { value: 'errands', label: 'Errands (grocery, pharmacy)' },
      { value: 'appointments', label: 'Doctor / dentist appointments' },
    ],
  },
];

export const responsibilitiesSection: Section = {
  id: 'responsibilities',
  title: 'Responsibilities',
  description: 'Define the au pair\'s daily responsibilities and per-child routines. We\'ll tailor questions to each child\'s age.',
  icon: '📋',
  estimatedMinutes: 15,
  questions: responsibilitiesQuestions,
};
