import type { Question, Section } from '@pair/types';

export const screenTimeMediaQuestions: Question[] = [
  {
    id: 'screen_time_philosophy',
    sectionId: 'screen_time_media',
    text: 'How would you describe your overall approach to screens and media for your children?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Screen time philosophy',
    options: [
      { value: 'minimal', label: 'Minimal', description: 'We keep screens very limited. Mostly educational content, tightly time-boxed.' },
      { value: 'moderate', label: 'Moderate', description: 'Screens are part of life but bounded. Clear daily limits.' },
      { value: 'flexible', label: 'Flexible', description: 'We adjust based on the day, what\'s happening, and the content.' },
      { value: 'open', label: 'Open', description: 'We don\'t place strict limits — we focus more on content than time.' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'screen_time_philosophy_notes',
    sectionId: 'screen_time_media',
    text: 'In your own words, describe your screen time philosophy.',
    subtext: 'This will appear directly in your household guide — write as if explaining it to your au pair.',
    answerType: 'free_text',
    required: true,
    documentLabel: 'Screen time — our approach',
    placeholder: 'e.g. We believe screens are fine in moderation and we don\'t stress about every minute. We do care a lot about what they watch — we avoid anything violent or commercial-heavy. Screens as a reward rather than a default...',
  },
  {
    id: 'no_screen_situations',
    sectionId: 'screen_time_media',
    text: 'Are there situations where screens are never allowed, regardless of other rules?',
    answerType: 'multi_choice',
    required: false,
    documentLabel: 'No screens ever during',
    options: [
      { value: 'meals', label: 'Mealtimes' },
      { value: 'before_school', label: 'Before school / daycare' },
      { value: 'first_hour_home', label: 'First hour after school' },
      { value: 'outside_time', label: 'During outdoor time' },
      { value: 'before_homework', label: 'Before homework is finished' },
      { value: 'one_hour_before_bed', label: '1 hour before bedtime' },
      { value: 'playdate', label: 'During playdates' },
    ],
  },

  // ── Per-child screen time ──────────────────────────────────────────────────
  {
    id: 'child_daily_screen_limit',
    sectionId: 'screen_time_media',
    text: 'What is {childName}\'s daily screen time limit?',
    answerType: 'single_choice',
    required: true,
    repeatFor: 'children_list',
    documentLabel: 'Daily screen time limit',
    options: [
      { value: 'none', label: 'No screen time' },
      { value: 'fifteen_min', label: '15 minutes' },
      { value: 'thirty_min', label: '30 minutes' },
      { value: 'forty_five_min', label: '45 minutes' },
      { value: 'one_hour', label: '1 hour' },
      { value: 'ninety_min', label: '90 minutes' },
      { value: 'two_hours', label: '2 hours' },
      { value: 'flexible_no_limit', label: 'No strict daily limit' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'child_approved_content',
    sectionId: 'screen_time_media',
    text: 'What content or apps is {childName} allowed to watch or use?',
    subtext: 'List approved shows, platforms, or app categories.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    documentLabel: 'Approved content',
    placeholder: 'e.g. Netflix: Peppa Pig, Bluey, Magic School Bus. YouTube Kids (supervised only). Educational apps: Khan Academy Kids, Duolingo...',
  },
  {
    id: 'child_restricted_content',
    sectionId: 'screen_time_media',
    text: 'What content or apps is {childName} NOT allowed to watch or use?',
    subtext: 'Include specific shows, platforms, game types, or content categories.',
    answerType: 'free_text',
    required: true,
    repeatFor: 'children_list',
    documentLabel: 'Restricted content',
    placeholder: 'e.g. No YouTube (main, only Kids). No Minecraft or Roblox. Nothing rated above TV-Y7. No ads-based content. No TikTok or social media...',
  },
  {
    id: 'child_device_rules',
    sectionId: 'screen_time_media',
    text: 'Which devices is {childName} allowed to use?',
    answerType: 'multi_choice',
    required: true,
    repeatFor: 'children_list',
    documentLabel: 'Approved devices',
    options: [
      { value: 'family_tv', label: 'Family TV (supervised)' },
      { value: 'family_tablet', label: 'Family tablet (supervised)' },
      { value: 'own_tablet', label: 'Their own tablet' },
      { value: 'parent_phone', label: 'Parent\'s phone (supervised)' },
      { value: 'gaming_console', label: 'Gaming console' },
      { value: 'laptop', label: 'Laptop / computer' },
      { value: 'smartwatch', label: 'Smartwatch' },
    ],
  },
  {
    id: 'child_gaming_rules',
    sectionId: 'screen_time_media',
    text: 'What are the gaming rules for {childName}?',
    answerType: 'free_text',
    required: false,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [
        { sourceQuestionId: 'child_device_rules', operator: 'includes', value: 'gaming_console' },
        { sourceQuestionId: '_repeat_context.age_months', operator: 'gte', value: 48 },
      ],
    },
    documentLabel: 'Gaming rules',
    placeholder: 'e.g. Nintendo Switch is allowed on weekends only, 1 hour max. Online multiplayer only with known friends. No in-app purchases ever...',
  },
  {
    id: 'child_social_media',
    sectionId: 'screen_time_media',
    text: 'What is your social media policy for {childName}?',
    answerType: 'single_choice',
    required: true,
    repeatFor: 'children_list',
    showIf: {
      logic: 'AND',
      conditions: [{ sourceQuestionId: '_repeat_context.age_months', operator: 'gte', value: 120 }],
    },
    documentLabel: 'Social media policy',
    options: [
      { value: 'no_social_media', label: 'No social media platforms at all' },
      { value: 'supervised_only', label: 'Supervised use only — we review content together' },
      { value: 'approved_platforms', label: 'Approved platforms with parental controls active' },
      { value: 'independent', label: 'Independent use — we\'ve had the conversation' },
    ],
  },
  {
    id: 'au_pair_phone_during_care',
    sectionId: 'screen_time_media',
    text: 'What is your policy on the au pair\'s own phone use during working hours?',
    answerType: 'single_choice',
    required: true,
    documentLabel: 'Au pair phone use during care',
    options: [
      { value: 'no_phone', label: 'No personal phone use while the children are in care', description: 'Phone away during working hours, except for emergencies.' },
      { value: 'emergencies_only', label: 'Emergencies and child-related communication only', description: 'Use for parent updates and emergencies. Not personal browsing or social media.' },
      { value: 'reasonable_use', label: 'Reasonable use — children engaged and safe', description: 'Use your judgement. Children\'s safety and engagement comes first.' },
      { value: 'flexible', label: 'Flexible — use common sense', description: 'We trust you to use your phone without it affecting care.' },
    ],
    feedsIntoModules: ['performance_review'],
  },
  {
    id: 'au_pair_phone_notes',
    sectionId: 'screen_time_media',
    text: 'Any additional notes on the phone policy?',
    answerType: 'free_text',
    required: false,
    documentLabel: 'Phone policy — additional notes',
    placeholder: 'e.g. Fine to check messages during nap time. Please don\'t have the phone out during meals or story time. The children notice and it sets an example...',
  },
];

export const screenTimeMediaSection: Section = {
  id: 'screen_time_media',
  title: 'Screen Time & Media',
  description: 'Document your screen time rules and media philosophy per child — one of the most common sources of unspoken friction.',
  icon: '📱',
  estimatedMinutes: 10,
  questions: screenTimeMediaQuestions,
};
